### ISSUE TITLE
Duplicate of QueuedHostedService and IBackgroundTaskQueue

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-WeChat#11]
So we have two versions of each: https://github.com/microsoft/botframework-solutions/blob/11efb3988a51c53b1012488b6b94356661d11dee/lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/TaskExtensions/QueuedHostedService.cs & https://github.com/microsoft/BotFramework-WeChat/blob/master/libraries/csharp_dotnetcore/Microsoft.Bot.Builder.Adapters.WeChat/QueuedHostedService.cs.
Do we do it on purpose or will they be merged into sdk in the future?

**Comment by youyu16** [comment]
Please use the full name of these classes, like Microsoft.Bot.Builder.Adapters.WeChat.QueuedHostedService & Microsoft.Bot.Builder.Solutions.TaskExtensions.QueuedHostedService
