### ISSUE TITLE
Can we hash the media url,not the image bytes?

### ISSUE THREAD

**Issue by aqliuyun** [microsoft/BotFramework-WeChat#37]
We should not download the media data every time in bot.The response will be slow.
Image that once the media size is too large,and many request, the server will boom.
We have to consider the concurrent request.same resource, upload too much times.

**Comment by youyu16** [comment]
Not using the URL to diff the image, because the same link can be different images. 
Uploading media action is already been running in the background and if the uploading request takes too long the request will be canceled.
