### ISSUE TITLE
Better method to convert HeroCard

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-WeChat#8]
Sometimes it does not contain neither Tap nor Images..

I also noticed that it is a very limited support for AdaptiveCard, sad..

**Comment by timenick** [comment]
> Sometimes it does not contain neither Tap nor Images..
> 
> I also noticed that it is a very limited support for AdaptiveCard, sad..

We mapped HeroCard to News message in WeChat. Images are required in news message. So you may not contain a tap but must have images in your HeroCard.
